// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, AMAFAppMetricaDeferredDeeplinkReasonPigeon) {
  AMAFAppMetricaDeferredDeeplinkReasonPigeonNOT_A_FIRST_LAUNCH = 0,
  AMAFAppMetricaDeferredDeeplinkReasonPigeonPARSE_ERROR = 1,
  AMAFAppMetricaDeferredDeeplinkReasonPigeonUNKNOWN = 2,
  AMAFAppMetricaDeferredDeeplinkReasonPigeonNO_REFERRER = 3,
  AMAFAppMetricaDeferredDeeplinkReasonPigeonNO_ERROR = 4,
};

typedef NS_ENUM(NSUInteger, AMAFUserProfileAttributeType) {
  AMAFUserProfileAttributeTypeBIRTH_DATE = 0,
  AMAFUserProfileAttributeTypeBOOLEAN = 1,
  AMAFUserProfileAttributeTypeCOUNTER = 2,
  AMAFUserProfileAttributeTypeGENDER = 3,
  AMAFUserProfileAttributeTypeNAME = 4,
  AMAFUserProfileAttributeTypeNOTIFICATION_ENABLED = 5,
  AMAFUserProfileAttributeTypeNUMBER = 6,
  AMAFUserProfileAttributeTypeSTRING = 7,
  AMAFUserProfileAttributeTypePHONE_HASH = 8,
  AMAFUserProfileAttributeTypeEMAIL_HASH = 9,
  AMAFUserProfileAttributeTypeTELEGRAM_LOGIN_HASH = 10,
};

typedef NS_ENUM(NSUInteger, AMAFGenderPigeon) {
  AMAFGenderPigeonMALE = 0,
  AMAFGenderPigeonFEMALE = 1,
  AMAFGenderPigeonOTHER = 2,
  AMAFGenderPigeonUNDEFINED = 3,
};

typedef NS_ENUM(NSUInteger, AMAFAdTypePigeon) {
  AMAFAdTypePigeonUNKNOWN = 0,
  AMAFAdTypePigeonNATIVE = 1,
  AMAFAdTypePigeonBANNER = 2,
  AMAFAdTypePigeonREWARDED = 3,
  AMAFAdTypePigeonINTERSTITIAL = 4,
  AMAFAdTypePigeonMREC = 5,
  AMAFAdTypePigeonAPP_OPEN = 6,
  AMAFAdTypePigeonOTHER = 7,
};

typedef NS_ENUM(NSUInteger, AMAFStartupParamsItemStatusPigeon) {
  AMAFStartupParamsItemStatusPigeonFEATURE_DISABLED = 0,
  AMAFStartupParamsItemStatusPigeonINVALID_VALUE_FROM_PROVIDER = 1,
  AMAFStartupParamsItemStatusPigeonNETWORK_ERROR = 2,
  AMAFStartupParamsItemStatusPigeonOK = 3,
  AMAFStartupParamsItemStatusPigeonPROVIDER_UNAVAILABLE = 4,
  AMAFStartupParamsItemStatusPigeonUNKNOWN_ERROR = 5,
};

@class AMAFAppMetricaConfigPigeon;
@class AMAFLocationPigeon;
@class AMAFPreloadInfoPigeon;
@class AMAFAppMetricaDeferredDeeplinkErrorPigeon;
@class AMAFAppMetricaDeferredDeeplinkPigeon;
@class AMAFAppMetricaDeferredDeeplinkParametersPigeon;
@class AMAFRevenuePigeon;
@class AMAFReceiptPigeon;
@class AMAFECommerceAmountPigeon;
@class AMAFECommerceProductPigeon;
@class AMAFECommercePricePigeon;
@class AMAFECommerceReferrerPigeon;
@class AMAFECommerceScreenPigeon;
@class AMAFECommerceCartItemPigeon;
@class AMAFECommerceOrderPigeon;
@class AMAFECommerceEventPigeon;
@class AMAFStackTraceElementPigeon;
@class AMAFErrorDetailsPigeon;
@class AMAFUserProfileAttributePigeon;
@class AMAFUserProfilePigeon;
@class AMAFAdRevenuePigeon;
@class AMAFStartupParamsItemPigeon;
@class AMAFStartupParamsResultPigeon;
@class AMAFStartupParamsReasonPigeon;
@class AMAFStartupParamsPigeon;
@class AMAFExternalAttributionPigeon;
@class AMAFReporterConfigPigeon;

@interface AMAFAppMetricaConfigPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithApiKey:(NSString *)apiKey
    advIdentifiersTracking:(nullable NSNumber *)advIdentifiersTracking
    anrMonitoring:(nullable NSNumber *)anrMonitoring
    anrMonitoringTimeout:(nullable NSNumber *)anrMonitoringTimeout
    appBuildNumber:(nullable NSNumber *)appBuildNumber
    appEnvironment:(nullable NSDictionary<NSString *, NSString *> *)appEnvironment
    appOpenTrackingEnabled:(nullable NSNumber *)appOpenTrackingEnabled
    appVersion:(nullable NSString *)appVersion
    crashReporting:(nullable NSNumber *)crashReporting
    customHosts:(nullable NSArray<NSString *> *)customHosts
    dataSendingEnabled:(nullable NSNumber *)dataSendingEnabled
    deviceType:(nullable NSString *)deviceType
    dispatchPeriodSeconds:(nullable NSNumber *)dispatchPeriodSeconds
    errorEnvironment:(nullable NSDictionary<NSString *, NSString *> *)errorEnvironment
    firstActivationAsUpdate:(nullable NSNumber *)firstActivationAsUpdate
    location:(nullable AMAFLocationPigeon *)location
    locationTracking:(nullable NSNumber *)locationTracking
    logs:(nullable NSNumber *)logs
    maxReportsCount:(nullable NSNumber *)maxReportsCount
    maxReportsInDatabaseCount:(nullable NSNumber *)maxReportsInDatabaseCount
    nativeCrashReporting:(nullable NSNumber *)nativeCrashReporting
    preloadInfo:(nullable AMAFPreloadInfoPigeon *)preloadInfo
    revenueAutoTrackingEnabled:(nullable NSNumber *)revenueAutoTrackingEnabled
    sessionTimeout:(nullable NSNumber *)sessionTimeout
    sessionsAutoTrackingEnabled:(nullable NSNumber *)sessionsAutoTrackingEnabled
    userProfileID:(nullable NSString *)userProfileID;
@property(nonatomic, copy) NSString * apiKey;
@property(nonatomic, strong, nullable) NSNumber * advIdentifiersTracking;
@property(nonatomic, strong, nullable) NSNumber * anrMonitoring;
@property(nonatomic, strong, nullable) NSNumber * anrMonitoringTimeout;
@property(nonatomic, strong, nullable) NSNumber * appBuildNumber;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * appEnvironment;
@property(nonatomic, strong, nullable) NSNumber * appOpenTrackingEnabled;
@property(nonatomic, copy, nullable) NSString * appVersion;
@property(nonatomic, strong, nullable) NSNumber * crashReporting;
@property(nonatomic, strong, nullable) NSArray<NSString *> * customHosts;
@property(nonatomic, strong, nullable) NSNumber * dataSendingEnabled;
@property(nonatomic, copy, nullable) NSString * deviceType;
@property(nonatomic, strong, nullable) NSNumber * dispatchPeriodSeconds;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * errorEnvironment;
@property(nonatomic, strong, nullable) NSNumber * firstActivationAsUpdate;
@property(nonatomic, strong, nullable) AMAFLocationPigeon * location;
@property(nonatomic, strong, nullable) NSNumber * locationTracking;
@property(nonatomic, strong, nullable) NSNumber * logs;
@property(nonatomic, strong, nullable) NSNumber * maxReportsCount;
@property(nonatomic, strong, nullable) NSNumber * maxReportsInDatabaseCount;
@property(nonatomic, strong, nullable) NSNumber * nativeCrashReporting;
@property(nonatomic, strong, nullable) AMAFPreloadInfoPigeon * preloadInfo;
@property(nonatomic, strong, nullable) NSNumber * revenueAutoTrackingEnabled;
@property(nonatomic, strong, nullable) NSNumber * sessionTimeout;
@property(nonatomic, strong, nullable) NSNumber * sessionsAutoTrackingEnabled;
@property(nonatomic, copy, nullable) NSString * userProfileID;
@end

@interface AMAFLocationPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithLatitude:(NSNumber *)latitude
    longitude:(NSNumber *)longitude
    provider:(nullable NSString *)provider
    altitude:(nullable NSNumber *)altitude
    accuracy:(nullable NSNumber *)accuracy
    course:(nullable NSNumber *)course
    speed:(nullable NSNumber *)speed
    timestamp:(nullable NSNumber *)timestamp;
@property(nonatomic, strong) NSNumber * latitude;
@property(nonatomic, strong) NSNumber * longitude;
@property(nonatomic, copy, nullable) NSString * provider;
@property(nonatomic, strong, nullable) NSNumber * altitude;
@property(nonatomic, strong, nullable) NSNumber * accuracy;
@property(nonatomic, strong, nullable) NSNumber * course;
@property(nonatomic, strong, nullable) NSNumber * speed;
@property(nonatomic, strong, nullable) NSNumber * timestamp;
@end

@interface AMAFPreloadInfoPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithTrackingId:(NSString *)trackingId
    additionalInfo:(nullable NSDictionary<NSString *, NSString *> *)additionalInfo;
@property(nonatomic, copy) NSString * trackingId;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * additionalInfo;
@end

@interface AMAFAppMetricaDeferredDeeplinkErrorPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithReason:(AMAFAppMetricaDeferredDeeplinkReasonPigeon)reason
    description:(NSString *)description
    message:(nullable NSString *)message;
@property(nonatomic, assign) AMAFAppMetricaDeferredDeeplinkReasonPigeon reason;
@property(nonatomic, copy) NSString * description;
@property(nonatomic, copy, nullable) NSString * message;
@end

@interface AMAFAppMetricaDeferredDeeplinkPigeon : NSObject
+ (instancetype)makeWithDeeplink:(nullable NSString *)deeplink
    error:(nullable AMAFAppMetricaDeferredDeeplinkErrorPigeon *)error;
@property(nonatomic, copy, nullable) NSString * deeplink;
@property(nonatomic, strong, nullable) AMAFAppMetricaDeferredDeeplinkErrorPigeon * error;
@end

@interface AMAFAppMetricaDeferredDeeplinkParametersPigeon : NSObject
+ (instancetype)makeWithParameters:(nullable NSDictionary<NSString *, NSString *> *)parameters
    error:(nullable AMAFAppMetricaDeferredDeeplinkErrorPigeon *)error;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * parameters;
@property(nonatomic, strong, nullable) AMAFAppMetricaDeferredDeeplinkErrorPigeon * error;
@end

@interface AMAFRevenuePigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPrice:(NSString *)price
    currency:(NSString *)currency
    quantity:(nullable NSNumber *)quantity
    productId:(nullable NSString *)productId
    payload:(nullable NSString *)payload
    receipt:(nullable AMAFReceiptPigeon *)receipt
    transactionId:(nullable NSString *)transactionId;
@property(nonatomic, copy) NSString * price;
@property(nonatomic, copy) NSString * currency;
@property(nonatomic, strong, nullable) NSNumber * quantity;
@property(nonatomic, copy, nullable) NSString * productId;
@property(nonatomic, copy, nullable) NSString * payload;
@property(nonatomic, strong, nullable) AMAFReceiptPigeon * receipt;
@property(nonatomic, copy, nullable) NSString * transactionId;
@end

@interface AMAFReceiptPigeon : NSObject
+ (instancetype)makeWithData:(nullable NSString *)data
    signature:(nullable NSString *)signature;
@property(nonatomic, copy, nullable) NSString * data;
@property(nonatomic, copy, nullable) NSString * signature;
@end

@interface AMAFECommerceAmountPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAmount:(NSString *)amount
    currency:(NSString *)currency;
@property(nonatomic, copy) NSString * amount;
@property(nonatomic, copy) NSString * currency;
@end

@interface AMAFECommerceProductPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSku:(NSString *)sku
    name:(nullable NSString *)name
    categoriesPath:(nullable NSArray<NSString *> *)categoriesPath
    payload:(nullable NSDictionary<NSString *, NSString *> *)payload
    actualPrice:(nullable AMAFECommercePricePigeon *)actualPrice
    originalPrice:(nullable AMAFECommercePricePigeon *)originalPrice
    promocodes:(nullable NSArray<NSString *> *)promocodes;
@property(nonatomic, copy) NSString * sku;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, strong, nullable) NSArray<NSString *> * categoriesPath;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * payload;
@property(nonatomic, strong, nullable) AMAFECommercePricePigeon * actualPrice;
@property(nonatomic, strong, nullable) AMAFECommercePricePigeon * originalPrice;
@property(nonatomic, strong, nullable) NSArray<NSString *> * promocodes;
@end

@interface AMAFECommercePricePigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithFiat:(AMAFECommerceAmountPigeon *)fiat
    internalComponents:(nullable NSArray<AMAFECommerceAmountPigeon *> *)internalComponents;
@property(nonatomic, strong) AMAFECommerceAmountPigeon * fiat;
@property(nonatomic, strong, nullable) NSArray<AMAFECommerceAmountPigeon *> * internalComponents;
@end

@interface AMAFECommerceReferrerPigeon : NSObject
+ (instancetype)makeWithType:(nullable NSString *)type
    identifier:(nullable NSString *)identifier
    screen:(nullable AMAFECommerceScreenPigeon *)screen;
@property(nonatomic, copy, nullable) NSString * type;
@property(nonatomic, copy, nullable) NSString * identifier;
@property(nonatomic, strong, nullable) AMAFECommerceScreenPigeon * screen;
@end

@interface AMAFECommerceScreenPigeon : NSObject
+ (instancetype)makeWithName:(nullable NSString *)name
    categoriesPath:(nullable NSArray<NSString *> *)categoriesPath
    searchQuery:(nullable NSString *)searchQuery
    payload:(nullable NSDictionary<NSString *, NSString *> *)payload;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, strong, nullable) NSArray<NSString *> * categoriesPath;
@property(nonatomic, copy, nullable) NSString * searchQuery;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * payload;
@end

@interface AMAFECommerceCartItemPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithProduct:(AMAFECommerceProductPigeon *)product
    quantity:(NSString *)quantity
    revenue:(AMAFECommercePricePigeon *)revenue
    referrer:(nullable AMAFECommerceReferrerPigeon *)referrer;
@property(nonatomic, strong) AMAFECommerceProductPigeon * product;
@property(nonatomic, copy) NSString * quantity;
@property(nonatomic, strong) AMAFECommercePricePigeon * revenue;
@property(nonatomic, strong, nullable) AMAFECommerceReferrerPigeon * referrer;
@end

@interface AMAFECommerceOrderPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithIdentifier:(NSString *)identifier
    items:(NSArray<AMAFECommerceCartItemPigeon *> *)items
    payload:(nullable NSDictionary<NSString *, NSString *> *)payload;
@property(nonatomic, copy) NSString * identifier;
@property(nonatomic, strong) NSArray<AMAFECommerceCartItemPigeon *> * items;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * payload;
@end

@interface AMAFECommerceEventPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithEventType:(NSString *)eventType
    cartItem:(nullable AMAFECommerceCartItemPigeon *)cartItem
    order:(nullable AMAFECommerceOrderPigeon *)order
    product:(nullable AMAFECommerceProductPigeon *)product
    referrer:(nullable AMAFECommerceReferrerPigeon *)referrer
    screen:(nullable AMAFECommerceScreenPigeon *)screen;
@property(nonatomic, copy) NSString * eventType;
@property(nonatomic, strong, nullable) AMAFECommerceCartItemPigeon * cartItem;
@property(nonatomic, strong, nullable) AMAFECommerceOrderPigeon * order;
@property(nonatomic, strong, nullable) AMAFECommerceProductPigeon * product;
@property(nonatomic, strong, nullable) AMAFECommerceReferrerPigeon * referrer;
@property(nonatomic, strong, nullable) AMAFECommerceScreenPigeon * screen;
@end

@interface AMAFStackTraceElementPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithClassName:(NSString *)className
    fileName:(nullable NSString *)fileName
    line:(NSNumber *)line
    column:(NSNumber *)column
    methodName:(NSString *)methodName;
@property(nonatomic, copy) NSString * className;
@property(nonatomic, copy, nullable) NSString * fileName;
@property(nonatomic, strong) NSNumber * line;
@property(nonatomic, strong) NSNumber * column;
@property(nonatomic, copy) NSString * methodName;
@end

@interface AMAFErrorDetailsPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithExceptionClass:(NSString *)exceptionClass
    message:(nullable NSString *)message
    dartVersion:(NSString *)dartVersion
    backtrace:(nullable NSArray<AMAFStackTraceElementPigeon *> *)backtrace;
@property(nonatomic, copy) NSString * exceptionClass;
@property(nonatomic, copy, nullable) NSString * message;
@property(nonatomic, copy) NSString * dartVersion;
@property(nonatomic, strong, nullable) NSArray<AMAFStackTraceElementPigeon *> * backtrace;
@end

@interface AMAFUserProfileAttributePigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithKey:(NSString *)key
    doubleValue:(nullable NSNumber *)doubleValue
    stringValue:(nullable NSString *)stringValue
    boolValue:(nullable NSNumber *)boolValue
    year:(nullable NSNumber *)year
    month:(nullable NSNumber *)month
    day:(nullable NSNumber *)day
    age:(nullable NSNumber *)age
    genderValue:(AMAFGenderPigeon)genderValue
    stringValues:(nullable NSArray<NSString *> *)stringValues
    ifUndefined:(nullable NSNumber *)ifUndefined
    reset:(nullable NSNumber *)reset
    type:(AMAFUserProfileAttributeType)type;
@property(nonatomic, copy) NSString * key;
@property(nonatomic, strong, nullable) NSNumber * doubleValue;
@property(nonatomic, copy, nullable) NSString * stringValue;
@property(nonatomic, strong, nullable) NSNumber * boolValue;
@property(nonatomic, strong, nullable) NSNumber * year;
@property(nonatomic, strong, nullable) NSNumber * month;
@property(nonatomic, strong, nullable) NSNumber * day;
@property(nonatomic, strong, nullable) NSNumber * age;
@property(nonatomic, assign) AMAFGenderPigeon genderValue;
@property(nonatomic, strong, nullable) NSArray<NSString *> * stringValues;
@property(nonatomic, strong, nullable) NSNumber * ifUndefined;
@property(nonatomic, strong, nullable) NSNumber * reset;
@property(nonatomic, assign) AMAFUserProfileAttributeType type;
@end

@interface AMAFUserProfilePigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAttributes:(NSArray<AMAFUserProfileAttributePigeon *> *)attributes;
@property(nonatomic, strong) NSArray<AMAFUserProfileAttributePigeon *> * attributes;
@end

@interface AMAFAdRevenuePigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAdRevenue:(NSString *)adRevenue
    currency:(NSString *)currency
    adType:(AMAFAdTypePigeon)adType
    adNetwork:(nullable NSString *)adNetwork
    adUnitId:(nullable NSString *)adUnitId
    adUnitName:(nullable NSString *)adUnitName
    adPlacementId:(nullable NSString *)adPlacementId
    adPlacementName:(nullable NSString *)adPlacementName
    precision:(nullable NSString *)precision
    payload:(nullable NSDictionary<NSString *, NSString *> *)payload;
@property(nonatomic, copy) NSString * adRevenue;
@property(nonatomic, copy) NSString * currency;
@property(nonatomic, assign) AMAFAdTypePigeon adType;
@property(nonatomic, copy, nullable) NSString * adNetwork;
@property(nonatomic, copy, nullable) NSString * adUnitId;
@property(nonatomic, copy, nullable) NSString * adUnitName;
@property(nonatomic, copy, nullable) NSString * adPlacementId;
@property(nonatomic, copy, nullable) NSString * adPlacementName;
@property(nonatomic, copy, nullable) NSString * precision;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * payload;
@end

@interface AMAFStartupParamsItemPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(nullable NSString *)id
    status:(AMAFStartupParamsItemStatusPigeon)status
    errorDetails:(nullable NSString *)errorDetails;
@property(nonatomic, copy, nullable) NSString * id;
@property(nonatomic, assign) AMAFStartupParamsItemStatusPigeon status;
@property(nonatomic, copy, nullable) NSString * errorDetails;
@end

@interface AMAFStartupParamsResultPigeon : NSObject
+ (instancetype)makeWithDeviceId:(nullable NSString *)deviceId
    deviceIdHash:(nullable NSString *)deviceIdHash
    parameters:(nullable NSDictionary<NSString *, AMAFStartupParamsItemPigeon *> *)parameters
    uuid:(nullable NSString *)uuid;
@property(nonatomic, copy, nullable) NSString * deviceId;
@property(nonatomic, copy, nullable) NSString * deviceIdHash;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, AMAFStartupParamsItemPigeon *> * parameters;
@property(nonatomic, copy, nullable) NSString * uuid;
@end

@interface AMAFStartupParamsReasonPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithValue:(NSString *)value;
@property(nonatomic, copy) NSString * value;
@end

@interface AMAFStartupParamsPigeon : NSObject
+ (instancetype)makeWithResult:(nullable AMAFStartupParamsResultPigeon *)result
    reason:(nullable AMAFStartupParamsReasonPigeon *)reason;
@property(nonatomic, strong, nullable) AMAFStartupParamsResultPigeon * result;
@property(nonatomic, strong, nullable) AMAFStartupParamsReasonPigeon * reason;
@end

@interface AMAFExternalAttributionPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSource:(NSString *)source
    data:(NSDictionary<NSString *, id> *)data;
@property(nonatomic, copy) NSString * source;
@property(nonatomic, strong) NSDictionary<NSString *, id> * data;
@end

@interface AMAFReporterConfigPigeon : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithApiKey:(NSString *)apiKey
    appEnvironment:(nullable NSDictionary<NSString *, NSString *> *)appEnvironment
    dataSendingEnabled:(nullable NSNumber *)dataSendingEnabled
    dispatchPeriodSeconds:(nullable NSNumber *)dispatchPeriodSeconds
    logs:(nullable NSNumber *)logs
    maxReportsCount:(nullable NSNumber *)maxReportsCount
    maxReportsInDatabaseCount:(nullable NSNumber *)maxReportsInDatabaseCount
    sessionTimeout:(nullable NSNumber *)sessionTimeout
    userProfileID:(nullable NSString *)userProfileID;
@property(nonatomic, copy) NSString * apiKey;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * appEnvironment;
@property(nonatomic, strong, nullable) NSNumber * dataSendingEnabled;
@property(nonatomic, strong, nullable) NSNumber * dispatchPeriodSeconds;
@property(nonatomic, strong, nullable) NSNumber * logs;
@property(nonatomic, strong, nullable) NSNumber * maxReportsCount;
@property(nonatomic, strong, nullable) NSNumber * maxReportsInDatabaseCount;
@property(nonatomic, strong, nullable) NSNumber * sessionTimeout;
@property(nonatomic, copy, nullable) NSString * userProfileID;
@end

/// The codec used by AMAFAppMetricaConfigConverterPigeon.
NSObject<FlutterMessageCodec> *AMAFAppMetricaConfigConverterPigeonGetCodec(void);

@protocol AMAFAppMetricaConfigConverterPigeon
/// @return `nil` only when `error != nil`.
- (nullable NSString *)toJsonConfig:(AMAFAppMetricaConfigPigeon *)config error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void AMAFAppMetricaConfigConverterPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AMAFAppMetricaConfigConverterPigeon> *_Nullable api);

/// The codec used by AMAFAppMetricaPigeon.
NSObject<FlutterMessageCodec> *AMAFAppMetricaPigeonGetCodec(void);

@protocol AMAFAppMetricaPigeon
- (void)activateConfig:(AMAFAppMetricaConfigPigeon *)config error:(FlutterError *_Nullable *_Nonnull)error;
- (void)activateReporterConfig:(AMAFReporterConfigPigeon *)config error:(FlutterError *_Nullable *_Nonnull)error;
- (void)clearAppEnvironmentWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)enableActivityAutoTrackingWithError:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSString *)getDeviceIdWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getLibraryApiLevelWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getLibraryVersionWithError:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSString *)getUuidWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)pauseSessionWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)putAppEnvironmentValueKey:(NSString *)key value:(nullable NSString *)value error:(FlutterError *_Nullable *_Nonnull)error;
- (void)putErrorEnvironmentValueKey:(NSString *)key value:(nullable NSString *)value error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportAdRevenueAdRevenue:(AMAFAdRevenuePigeon *)adRevenue error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportAppOpenDeeplink:(NSString *)deeplink error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportECommerceEvent:(AMAFECommerceEventPigeon *)event error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportErrorError:(AMAFErrorDetailsPigeon *)error message:(nullable NSString *)message error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportErrorWithGroupGroupId:(NSString *)groupId error:(nullable AMAFErrorDetailsPigeon *)error message:(nullable NSString *)message error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportEventEventName:(NSString *)eventName error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportEventWithJsonEventName:(NSString *)eventName attributesJson:(nullable NSString *)attributesJson error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportExternalAttributionExternalAttributionPigeon:(AMAFExternalAttributionPigeon *)externalAttributionPigeon error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportReferralUrlReferralUrl:(NSString *)referralUrl error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportRevenueRevenue:(AMAFRevenuePigeon *)revenue error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportUnhandledExceptionError:(AMAFErrorDetailsPigeon *)error error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportUserProfileUserProfile:(AMAFUserProfilePigeon *)userProfile error:(FlutterError *_Nullable *_Nonnull)error;
- (void)requestDeferredDeeplinkWithCompletion:(void (^)(AMAFAppMetricaDeferredDeeplinkPigeon *_Nullable, FlutterError *_Nullable))completion;
- (void)requestDeferredDeeplinkParametersWithCompletion:(void (^)(AMAFAppMetricaDeferredDeeplinkParametersPigeon *_Nullable, FlutterError *_Nullable))completion;
- (void)requestStartupParamsParams:(NSArray<NSString *> *)params completion:(void (^)(AMAFStartupParamsPigeon *_Nullable, FlutterError *_Nullable))completion;
- (void)resumeSessionWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)sendEventsBufferWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)setAdvIdentifiersTrackingEnabled:(NSNumber *)enabled error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setDataSendingEnabledEnabled:(NSNumber *)enabled error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setLocationLocation:(nullable AMAFLocationPigeon *)location error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setLocationTrackingEnabled:(NSNumber *)enabled error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setUserProfileIDUserProfileID:(nullable NSString *)userProfileID error:(FlutterError *_Nullable *_Nonnull)error;
- (void)handlePluginInitFinishedWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)touchReporterApiKey:(NSString *)apiKey error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void AMAFAppMetricaPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AMAFAppMetricaPigeon> *_Nullable api);

/// The codec used by AMAFAppMetricaLibraryAdapterPigeon.
NSObject<FlutterMessageCodec> *AMAFAppMetricaLibraryAdapterPigeonGetCodec(void);

@protocol AMAFAppMetricaLibraryAdapterPigeon
- (void)subscribeForAutoCollectedDataApiKey:(NSString *)apiKey error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void AMAFAppMetricaLibraryAdapterPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AMAFAppMetricaLibraryAdapterPigeon> *_Nullable api);

/// The codec used by AMAFReporterPigeon.
NSObject<FlutterMessageCodec> *AMAFReporterPigeonGetCodec(void);

@protocol AMAFReporterPigeon
- (void)clearAppEnvironmentApiKey:(NSString *)apiKey error:(FlutterError *_Nullable *_Nonnull)error;
- (void)pauseSessionApiKey:(NSString *)apiKey error:(FlutterError *_Nullable *_Nonnull)error;
- (void)putAppEnvironmentValueApiKey:(NSString *)apiKey key:(NSString *)key value:(nullable NSString *)value error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportAdRevenueApiKey:(NSString *)apiKey adRevenue:(AMAFAdRevenuePigeon *)adRevenue error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportECommerceApiKey:(NSString *)apiKey event:(AMAFECommerceEventPigeon *)event error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportErrorApiKey:(NSString *)apiKey error:(AMAFErrorDetailsPigeon *)error message:(nullable NSString *)message error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportErrorWithGroupApiKey:(NSString *)apiKey groupId:(NSString *)groupId error:(nullable AMAFErrorDetailsPigeon *)error message:(nullable NSString *)message error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportEventApiKey:(NSString *)apiKey eventName:(NSString *)eventName error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportEventWithJsonApiKey:(NSString *)apiKey eventName:(NSString *)eventName attributesJson:(nullable NSString *)attributesJson error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportRevenueApiKey:(NSString *)apiKey revenue:(AMAFRevenuePigeon *)revenue error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportUnhandledExceptionApiKey:(NSString *)apiKey error:(AMAFErrorDetailsPigeon *)error error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportUserProfileApiKey:(NSString *)apiKey userProfile:(AMAFUserProfilePigeon *)userProfile error:(FlutterError *_Nullable *_Nonnull)error;
- (void)resumeSessionApiKey:(NSString *)apiKey error:(FlutterError *_Nullable *_Nonnull)error;
- (void)sendEventsBufferApiKey:(NSString *)apiKey error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setDataSendingEnabledApiKey:(NSString *)apiKey enabled:(NSNumber *)enabled error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setUserProfileIDApiKey:(NSString *)apiKey userProfileID:(nullable NSString *)userProfileID error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void AMAFReporterPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AMAFReporterPigeon> *_Nullable api);

/// The codec used by AMAFInitialDeepLinkHolderPigeon.
NSObject<FlutterMessageCodec> *AMAFInitialDeepLinkHolderPigeonGetCodec(void);

@protocol AMAFInitialDeepLinkHolderPigeon
- (nullable NSString *)getInitialDeeplinkWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void AMAFInitialDeepLinkHolderPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AMAFInitialDeepLinkHolderPigeon> *_Nullable api);

NS_ASSUME_NONNULL_END
